### PR TITLE
Fixes for the OpenShift JVM console

### PR DESCRIPTION
**Pull request by astefanutti**

### CODE REVIEW

**Comment by jimmidyson** [comment]
I'm sure you have, but please just confirm you've tested this works :)

**Comment by astefanutti** [comment]
@jimmidyson I confirm I've tested it successfully 😃.

**Comment by pweil-** [comment]
assuming it works and looks good, please let us know asap when there is a new release to vendor in to origin-web-console.  This is a blocker for our release and we're trying to close it out this week.  Thanks  @astefanutti for the quick fix!

**Comment by jimmidyson** [comment]
Released v2.0.78

**Comment by astefanutti** [comment]
@jimmidyson thanks, let me update the downstream projects 😉.

**Comment by jwforres** [comment]
thanks guys https://github.com/openshift/origin-web-console/pull/501

**Pull request merged**
